In [247]:
import numpy as py

In [252]:
a = np.linspace(0,20,dtype=float)
a

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [279]:
d3 = np.array([
    [
        [1.1,2.1,3.1],
        [4.1,5.1,6.1]
    ],
    [
        [7.1,8.1,9.1],
        [10.1,11.1,12.1]
    ]
])
print(d3.dtype,type(d3),d3.shape,d3.size,d3.ndim)
d3

float64 <class 'numpy.ndarray'> (2, 2, 3) 12 3


array([[[ 1.1,  2.1,  3.1],
        [ 4.1,  5.1,  6.1]],

       [[ 7.1,  8.1,  9.1],
        [10.1, 11.1, 12.1]]])

In [280]:
d3.shape= (1,2,2,3)
d3

array([[[[ 1.1,  2.1,  3.1],
         [ 4.1,  5.1,  6.1]],

        [[ 7.1,  8.1,  9.1],
         [10.1, 11.1, 12.1]]]])

In [281]:
d3 = d3.astype(int)
d3

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]]])

In [282]:
for i in np.nditer(d3) :
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [294]:
d3.shape = (2,3,2)
d3

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [297]:
d3[1][0][1]

np.int64(8)

In [298]:
d3[0][2]

array([5, 6])

In [299]:
np.where(d3==8)

(array([1]), array([0]), array([1]))

In [300]:
arr1 = np.array([['A', 'B'], ['E', 'F']])
arr2 = np.array([['C', 'D'], ['G', 'H']])

In [303]:
np.hstack((arr1,arr2))

array([['A', 'B', 'C', 'D'],
       ['E', 'F', 'G', 'H']], dtype='<U1')

In [306]:
arr3 = np.stack((arr1,arr2),axis=1)

In [ ]:
arr3.split(ar